@Library('jenkins-shared-library') _
pipeline {
    agent {
        label 'jenkins-slave' 
    }
    environment {
        GITHUB_REPO_URL = 'https://github.com/abdelhamed-4A/CloudDevOpsProject.git'
        REPO_NAME = 'CloudDevOpsProject'
        GITHUB_REPO_BRANCH = 'main'
        DOCKER_REGISTRY = "abdelhamed4a"
        DOCKER_IMAGE = "java-web-app"
        IMAGE_TAG = "v${BUILD_NUMBER}"
        DOCKERHUB_CRED_ID = "dockerhub"
        EMAIL = "abdelhamednasser2@gmail.com"
        GIT_USERNAME = "abdelhamed-4A" 
        GIT_CRED_ID = "github"
        DEPLOYMENT = 'deployment.yaml' 
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: GITHUB_REPO_URL, branch: GITHUB_REPO_BRANCH    
            }
        }
        stage('Unit Test') {
            steps {
                dir('app') {  
                    unitTest()
                }
            }
        }
        stage('Build JAR') {
            steps {
                dir('app') {  
                    buildJar()
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
               dir('app'){
                sonarQubeAnalysis()
               }
            }
        }
                
        stage('Manage Docker Image') {
            steps {
                dir('app') {  
                    script {
                    BuildandPushDockerimage("${DOCKERHUB_CRED_ID}", "${DOCKER_REGISTRY}", "${DOCKER_IMAGE}", "${IMAGE_TAG}")
                }
                }                
            }
        }
        stage('Update Manifests') {
            steps {
                dir('kubernetes') {  
                    script {
                        updateManifests("${DOCKER_REGISTRY}", "${DOCKER_IMAGE}", "${IMAGE_TAG}", "${DEPLOYMENT}")
                    }
                }
            }   
        }             
        stage('Push Manifests') {
            steps {
                dir('kubernetes') {  
                    script {
                        pushManifests("${REPO_NAME}", "${GIT_USERNAME}", "${EMAIL}", "${GIT_CRED_ID}")
                    }
                }
            }            
        }
        
    }

    post {
        success {
            echo "Deployment successful!"
        }
        failure {
            echo "Build or deployment failed."
        }
    }
}




